### ISSUE TITLE
Emails sent to private or no-reply emails

### ISSUE THREAD

**Issue by adborden** [goodeggs/goodeggs-fairy#2]
Folks are all over the place with their emails. Even if email is correct in git, github will behave differently for web-based operations:

If I have my email set to private:

> We will use adborden@users.noreply.github.com when performing web-based Git operations and sending email on your behalf. If you want command line Git operations to use your private email you must set your email in Git.

If I have my personal email set as public, that address is used.

We want these emails to be effective and actionable so we probably should have an email address translation to ensure these emails are going to work addresses.

**Comment by bobzoller** [comment]
:(

how about key-pository contains a mapping file, and we can periodically
grab it via github raw url.

**Comment by adborden** [comment]
Oh! I like that idea. key-pository is more like a "directory" or a rolodex for eng.

Just thinking outload here, @TheBigSadowski and @hurrymaplelad s' teams were also playing with pairing, and explicitly tagging commits with both names pairing. Pivotal actually had a command line tool in their chef dev setup that had all the developers' initials along with a shell util that you could declare who you're pairing with. It would change your git email to something like eng+ab+bz@goodeggs.com or something based on who you were pairing with. If we found having that level of record keeping useful, we could head in that direction, too.

**Comment by bobzoller** [comment]
fixed in 4c9e7b246a7956ac8657ba2bc9fb8a851f667c62
